language: ruby
cache: bundler
rvm:
  - 2.1.2
bundler_args: --without production
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
  - bundle exec rake db:migrate RAILS_ENV=test
