# Use sqlite for dev environment
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

# Use sqlite for test environment
# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# Bring out the big guns for production
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: blog_development
#   pool: 5
#   username: 
#   password: 
