# Uncomment the following lines to use secrets.yml in a development environment
# Run `rake secret | pbcopy` to get a randomly generated secret token
development:
  secret_key_base: e8e9f3ca8193944186c92555d54e6729f801cc56d8e547cf87e77a4aea5919bb86920fbdff823b10a29a6c79fab20316474493b7174f50a95ca8bf08d1944267

# Uncomment the following lines to use secrets.yml in a test environment
# Run `rake secret | pbcopy` to get a randomly generated secret token
test:
  secret_key_base: 1022c8e3ab4632b9a5e7466b49498031b4b461bf0339585e165f0e71542ef10e9f747cd68db3ed8edfd5929600bcaf1c5554fb80f1a31262df1690f8f4ceb063

# Uncomment the following lines to use secrets.yml in a production environment
# production:
#   secret_key_base:
#   ip_address:
#   stathat_ez_api_key:
#   ga_tracker:
