# Uncomment the following lines to use secrets.yml in a development environment
# Run `rake secret | pbcopy` to get a randomly generated secret token
development:
  secret_key_base: foo

# Uncomment the following lines to use secrets.yml in a test environment
# Run `rake secret | pbcopy` to get a randomly generated secret token
test:
  secret_key_base: bar

# Uncomment the following lines to use secrets.yml in a production environment
production:
  secret_key_base: ENV['SECRET_KEY_BASE']
  ip_address: ENV['IP_ADDRESS']
  twitter_api_key: ENV['TWITTER_API_KEY']
  twitter_api_secret: ENV['TWITTER_API_SECRET']
  twitter_access_token: ENV['TWITTER_ACCESS_TOKEN']
  twitter_access_token_secret: ENV['TWITTER_ACCESS_TOKEN_SECRET']
  ga_tracker: ENV['GA_TRACKER']
